config/routes.rb
Rails.application.routes.draw do
  root 'sessions#index'
  get '/login' => 'sessions#new'
  post '/login' => "sessions#create"
  delete '/logout' => "sessions#destroy"
  get '/logoutcheck' => "sessions#verify"
  post '/logoutcheck' => "sessions#destroy"

  get 'quotes/new', to: "quotes#new1"
  post 'quotes/new', to: "quotes#add"
  post 'quotes/add', to: 'quotes#add'
  get 'quotes/newbook', to: "quotes#newbook"
  post 'quotes/newbook', to: "quotes#create2"
  get 'quotes/newmovie', to: "quotes#newmovie"
  post 'quotes/newmovie', to: "quotes#create2"
  get 'quotes/user_quotes', to: "quotes#user_quotes", as: "user_quotes"
  resources :quotes, only: [:index, :show, :edit, :update, :delete]

  resources :tags
  resources :books
  get 'users/:id/my_books', to: "users#my_books", as: "my_books"
  get 'users/:id/my_movies', to: "users#my_movies", as: 'my_movies'

  resources :users
  resources :movies

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
    has_many :quotes
    has_many :books, through: :quotes
    has_many :movies, through: :quotes
    validates :first_name, presence:true
    validates :user_name, presence:true, uniqueness:true
    validates :email, uniqueness:true
    validates :password, presence:true, length: {minimum: 6}
    has_secure_password
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    before_action :authorized, only: [:index, :show, :edit, :update, :delete]

  def index
  end

  def user_quotes
    @quotes = @user.quotes
  end

  def new
    @user = User.new
  end

  def create
    user = User.create(user_params)
    if user.save 
        session[:user_id] = user.id
        @user = current_user
        redirect_to user_path(@user)
    else
        flash[:notice] = user.errors.full_messages
        redirect_to(controller: 'users', action: 'new')
    end
  end

  def show
    @user = User.find(params[:id])
  end

  def my_books
    @user = current_user
    @books = @user.books
  end

  def my_movies
    @user = current_user
    @movies = @user.movies
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    @user.update(user_params)
    redirect_to @user
  end

  def delete
    @user = User.find(params[:id])
  end

private
  def user_params
    params.require(:user).permit(:first_name, :last_name, :user_name, :email, :password, :fave_book, :fave_movie, :password_confirmation)
  end
end




  

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/edit.html.erb
<div class="spacer"><h1>Edit Your Info</h1></div>

<%= form_for @user do |f| %>
  <fieldset>
  <p style='color:black; margin-bottom: 10px;'>Basic Info:</p>
  <div class='indent'>
    <p><font size='4'><%= f.label :first_name %></font>
    <%= f.text_field :first_name %></p>
  
    <p><font size='4'><%= f.label :last_name %></font>
    <%= f.text_field :last_name %></p>
  
    <p><font size='4'><%= f.label :email %></font>
    <%= f.text_field :email %></p>
  
    <p><font size='4'><%= f.label :user_name %></font>
    <%= f.text_field :user_name %></p>
    </div>
    <p style="color: black">Apologies, you are not able to change your password at this time.</p>

    <div class='indent'>
  <p style="margin-bottom: 7px;"><font size='4'><%= f.label :fave_book %></font>
    <%= f.collection_select :fave_book, Book.all, :id, :title, include_blank:true  %></p>
    &emsp;(If you need to add a new book, head to the <%=link_to "books page", books_path%> and scroll to the bottom.)
      <br><br>
    <p style="margin-bottom: 7px;"><font size='4'><%= f.label :fave_movie %></font>
    <%= f.collection_select :fave_movie, Movie.all, :id, :title, include_blank:true %></p>
    &emsp;(If you need to add a new movie, head to the <%=link_to "movies page", movies_path%> and scroll to the bottom.)
  
    <p style='margin-top: 30px;'><%= f.submit "Update" %></p>
      <% end %>
      </div>
  
    <% if flash[:notice] %>
      <% flash[:notice].each {|msg| %>
        <%= msg %>
      <% } %>
      <% end %>
      </fieldset>

app/views/users/index.html.erb
<% unless logged_in? %>
    <%flash[:notice] = "You must be logged in to see this page"%>
    <% redirect_to login_path %>
    <% end %>

app/views/users/my_books.html.erb
<div class="spacer"><h1>My Books</h1></div>
<h3>A veritable library!</h3>
<br>
<div>
<ol>
<% @books.each do |book| %>
    <li><span class='title'><%=link_to book.title, book_path(book) %></span><br>
    &emsp; <%= book.author %></li><br>
    <%end%>
</ol>
</div>

app/views/users/my_movies.html.erb
<div class="spacer"><h1>My Movies</h1></div>
<h3>A cinematic collection beyond compare!</h3>
<br>
<div>
<ol>
<% @movies.each do |movie| %>
    <li><span class='title'><%=link_to movie.title, movie_path(movie) %></span><br>
    &emsp; <%= movie.director %></li><br>
    <%end%>
</ol>
</div>

app/views/users/new.html.erb
<div class="spacer"><h1>Sign up & Join TagLine</h1></div>
<% if flash[:notice] %>
<h4>Womp womp...</h4>
<% flash[:notice].each {|msg| %>
  <div class='warning'><%= msg %></div>
<% } %>
<br>
<% end %>
<fieldset>
<legend><font size='4'>Give me the Deets</font></legend>
<%= form_for @user, controller: 'users', action: 'create' do |f| %>

    <p>First Name: <%= f.text_field :first_name %></p>
    <p>Last Name: <%= f.text_field :last_name %></p>
    <p>Email Address: <%= f.text_field :email %></p>
    <br>

    <p>Username: <%= f.text_field :user_name %></p>
    <p>Password: <%= f.password_field :password %>
    &ensp;Password Confirmation: <%= f.password_field :password_confirmation %></p>
    <br>

    <h3>It may be impossible but... </h3>
    <h5>What is your favorite book? <h5>
  <br><%= f.text_field :fave_book %><br>

    <h5>Can you do it? Can you pick one? How about your favorite movie?</h4>
      <p><%= f.text_field :fave_movie %></p>


    <%= f.submit "Submit" %>
   <% end %>
   

app/views/users/show.html.erb
<div class="spacer"><h1 style='color: rgb(15, 208, 95)'>Welcome, <%=@user.first_name%>!</h1></div>

<h2 style="padding-left: 10px; padding-bottom: 10px">Profile Information</h2>
<fieldset>
<legend><font size='5'>Biographic</font></legend>
<div class="facts"><p><b><font size='4'>First Name: </font></b> <%=@user.first_name %></p>
<p><b><font size='4'>Last Name: </font></b> <%=@user.last_name %></p>
<p><b><font size='4'>Email Address: </font></b> <%=@user.email %></p>

</fieldset>
<br>

<fieldset>
<legend><font size='5'>TagLine Deets</font></legend>
<div class="facts"><p><b><font size='4'>User Name: </font></b> <%=@user.user_name %></p>
<p><b><font size='4'>Fave Book: </font></b> 
  <% if !@user.fave_book.empty? %>
    <% if Book.find_by(title: @user.fave_book) %>
      <%=link_to @user.fave_book, book_path(Book.find_by(title: @user.fave_book)) %></p>
    <% else %>
      <%= @user.fave_book %>
    <% end %>
  <% else %>
    Alas, you have yet to pick one. </p>
<%end %>

    <p><b><font size='4'>Fave Movie: </font></b> 
  <% if !@user.fave_movie.empty? %>
    <% if Movie.find_by(title: @user.fave_movie) %>
      <%=link_to @user.fave_movie, movie_path(Movie.find_by(title: @user.fave_movie)) %></p>
    <% else %>
    <%= @user.fave_movie %></p>
    <% end %>
  <% else %>
    Alas, you have yet to pick one. </p>
  <% end %>

    <p style="margin-bottom: 8px;"><b><font size='4'>See your Fave Quotes: </font></b> 
    <u><%= link_to "My Favorite Quotes", user_quotes_path, method: :get %></u></p>
    <% if !@user.quotes.empty? %>
      &emsp;To whet your appetite... : "<%= @user.quotes.sample.quote %>"
    <% end %>
    <br><br>
    <br>
  <%= button_to 'Edit your Info', edit_user_path(@user), {:method=>'get'} %>
  <%=button_to "LOGOUT", '/logout', method: :delete %>
  </div>
  </fieldset>

<br>
<div class='scrolling-quote'>

</div>


  <br>
  <br>
<% if @user == current_user %>
  <fieldset>
  <legend><b>Danger zone</b></legend>
  <div class="facts">
  <%=button_to "DELETE User", '/users/delete', method: :delete %>
  <% end %>
  </div>
  </fieldset>

app/views/users/user_quotes.html.erb
<div class="spacer"><h1>Your Favorite Quotes</h1></div>

<% if !@quotes %>
    <p>You have no favorite quotes yet. :o( </p><br>
    (But you could - and should - change that!)
    <br>
    <%=button_to "Add a Quote!", quotes_new_path, :method=>'get' %>
<% else %>
    <ol>
    <% @quotes.each do |quote| %>
        <li><%=quote.quote%>
        <% if quote.book? %>
            source = Book.find(quote.book_id)
        <% else %>
            source = Movie.find(quote.movie_id)
        <% end %>
        <br>
        From <span class='title'><%=source.title%></span>
        <% if quote.author %>
            ~<%=quote.author%>
        <%end%></li>
    <% end %>
<% end %>