config/routes.rb
Rails.application.routes.draw do
  root 'sessions#index'
  get '/login' => 'sessions#new'
  post '/login' => "sessions#create"
  delete '/logout' => "sessions#destroy"
  get '/logoutcheck' => "sessions#verify"
  post '/logoutcheck' => "sessions#destroy"

  get 'quotes/new', to: "quotes#new1"
  post 'quotes/new', to: "quotes#add"
  post 'quotes/add', to: 'quotes#add'
  get 'quotes/newbook', to: "quotes#newbook"
  post 'quotes/newbook', to: "quotes#create2"
  get 'quotes/newmovie', to: "quotes#newmovie"
  post 'quotes/newmovie', to: "quotes#create2"
  get 'quotes/user_quotes', to: "quotes#user_quotes", as: "user_quotes"
  resources :quotes, only: [:index, :show, :edit, :update, :delete]

  resources :tags
  resources :books
  get 'users/:id/my_books', to: "users#my_books", as: "my_books"
  get 'users/:id/my_movies', to: "users#my_movies", as: 'my_movies'

  resources :users
  resources :movies

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/book.rb
class Book < ApplicationRecord
    has_many :quotes
    has_many :users, through: :quotes
    validates :title, presence:true, uniqueness:true
    accepts_nested_attributes_for :quotes

    def quotes_attributes=(quotes_attributes)
        quotes_attributes.values.each do |quote_attributes|
            self.quotes.build(quote_attributes)
        end
    end

end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :current_user, only: [:edit, :udpate, :destroy]
  skip_before_action :authorized, only: [:index, :new, :create]

  def index 
    @books = Book.all
    render :layout => "allbooks"
  end

  def my_books
    @user = current_user
    @books = @user.books
  end

  def new
    @book = Book.new
  end

  def create
    @book = Book.create(book_params)
    redirect_to @book
  end

  def show
    @book = Book.find(params[:id])
  end

  def edit
    @book = Book.find(params[:id])
  end

  def update
    @book = Book.find(params[:id])
    @book.update(book_params)
    redirect_to @book
  end

  def delete
    @book = Book.find(params[:id])
  end

private
  def book_params
    params.require(:book).permit(:book, :title, :author, :synopsis, :quotes_attributes => [:quote, :notes, :user_id, :book_id])
  end
  
end

app/helpers/books_helper.rb
module BooksHelper
end

app/views/books/_form.html.erb
<%= form_for @book do |f| %>
    <p><%=f.label :title %>
    <%=f.text_field :title %></p>
    <p><%=f.label :author %>
    <%=f.text_field :author %></p><br>
    <p><%=f.label :synopsis %>
    <%=f.text_area :synopsis%></p><br>

    <fieldset>
    <legend><font size='4'>Have a Favorite Quote to Add?</font></legend>
    <% if !!current_user %>
        <div class="facts"><%=f.fields_for :quote do |ff| %>
            <p><font size='3'><b><%=ff.label :quote %></b>
            <%=ff.text_area :quote %></p>

            <p><font size='3'><b><%=ff.label :notes %></b></font>
            <%=ff.text_area :notes %></p>
            <%= ff.hidden_field :user_id => current_user.id %>
            <%= ff.hidden_field :book_id => @book.id %>
            <% end %>
            </div>
    <% else %>
        <%=link_to "Log in", '/login'%> to start adding and saving quotes!
    <% end %>
    </fieldset><br>

    <%=f.submit "Submit"%>

<br>
<%end%>

app/views/books/edit.html.erb
<div class="spacer"><h1>Edit a Book</h1></div>

Found a mistake? Need to update a synopsis? Fill in the following form to submit an edit request.

<%= render 'form' %>

app/views/books/index.html.erb
<div class="spacer"><h1>All the Books</h1></div>

<div class="leftlist"><h3>A veritable library!</h3></div>
<br>
<div>
<ol>
<% @books.each do |book| %>
    <li><span class='title'><%=link_to book.title, book_path(book) %></span><br>
    &emsp; <%= book.author %></li><br>
    <%end%>
</ol>
<br><br><br>
</div>
<fieldset>
<%=button_to "Add a New Book", new_book_path, :method=>'get' %>
</fieldset>

app/views/books/new.html.erb
<div class="spacer"><h1>Enter a New Book into the Database</h1></div>

<%= render 'form' %>

app/views/books/show.html.erb
<div class="spacer"><h1>All About <%=@book.title.titlecase%></h1></div>

<fieldset>
<legend><font size='5'>Straight Up Facts</font></legend>
<div class="facts"><b><font size='4'>Title: </font></b> <%=@book.title.titlecase%><br>
<b><font size='4'>Author: </font></b> <%=@book.author%><br><br>
<b><font size='4'>Synopsis: </font></b>
<p>&emsp; <%=@book.synopsis%></p>
<%= button_to "Change/Edit/Update", {:controller => "books", :action => "edit", :book_id => @book.id} , :method => :get %>
</fieldset>
<br>

<fieldset>
<legend><font size='5'>Quality Quotes</font></legend>
<div class="facts"><b><font size='4'>Your favorite line: </b></font><br>

    <% if !@user.books || !@user.books.include?(@book) %>
        <p>&emsp;None yet entered.</p> <br>
        <%= button_to "Let's fix that!", quotes_new_path, {method: 'get'} %>
    <% elsif @user.books.include?(@book) %>
        <% favorite_line = Quote.find_by(user_id: @user, book_id: @book.id) %>
        <p>&emsp;<%= favorite_line %></p> <br>
        <%= button_to "Change/Edit/Update", `quotes/#{@favorite_line.id}/edit` %>
    <br>
    <% end %>

    <% lines = Quote.where(book_id: @book.id) %>
    <% if !lines.empty? %>
        <% sample = lines.take(5) %>
        <br><br>
        Some other folks' favorites:
    <ul>
        <% sample.each do |quote| %>
        <%= quote.quote %>
        <% end %>
        </ul>
    <%end%>
    </div>
</fieldset>
</div>